/*
 * This file is generated by jOOQ.
 */
package by.bntu.fitr.authenticationservice.dao.jooq;


import by.bntu.fitr.authenticationservice.dao.jooq.tables.Permission;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.Role;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.RolePermissions;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.permission</code>.
     */
    public final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PERMISSION_ID_SEQ,
            Sequences.ROLE_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Permission.PERMISSION,
            Role.ROLE,
            RolePermissions.ROLE_PERMISSIONS,
            User.USER);
    }
}
