/*
 * This file is generated by jOOQ.
 */
package by.bntu.fitr.authenticationservice.dao.jooq;


import by.bntu.fitr.authenticationservice.dao.jooq.tables.Permission;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.Role;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.RolePermissions;
import by.bntu.fitr.authenticationservice.dao.jooq.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public static final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
